# Development overrides
version: '3.8'

services:
  backend:
    environment:
      - LOG_LEVEL=DEBUG
      - DEBUG=true
    volumes:
      - ./backend:/app:rw
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]

  frontend:
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
    stdin_open: true
    tty: true