"""Shared enums for models."""

from enum import Enum


class InvestorEntityType(Enum):
    """Investor entity type enumeration."""
    CORPORATION = "Corporation"
    LIMITED_PARTNERSHIP = "Limited Partnership"
    EXEMPT_ORGANIZATION = "Exempt Organization"
    LLC_TAXED_AS_PARTNERSHIP = "LLC_Taxed as Partnership"
    INDIVIDUAL = "Individual"
    TRUST = "Trust"
    S_CORPORATION = "S Corporation"
    PARTNERSHIP = "Partnership"
    JOINT_TENANCY_TENANCY_IN_COMMON = "Joint Tenancy / Tenancy in Common"
    GOVERNMENT_BENEFIT_PLAN = "Government Benefit Plan"
    IRA_KEOGH = "IRA/Keogh"
    EXEMPT_ORGANIZATION_BENEFIT = "Exempt Organization_Benefit"
    LLP = "LLP"
    BENEFIT_PLAN_INVESTOR_ERISA_TITLE_I = "Benefit Plan Investor [ERISA Title I Plan]"
    GRANTOR_TRUST = "Grantor Trust"
    LLC_TAXED_AS_CORPORATION = "LLC_Taxed as Corporation"
    LLC_TAXED_AS_PARTNERSHIP_ALT = "LLC – Taxed as Partnership"
    ESTATE = "Estate"
    BENEFIT_PLAN_INVESTOR_PLAN_ASSETS = "Benefit Plan Investor [Plan Assets Entity_ERISA 3(42)]"


class USJurisdiction(Enum):
    """US states and DC jurisdiction enumeration."""
    AL = "AL"
    AK = "AK"
    AZ = "AZ"
    AR = "AR"
    CA = "CA"
    CO = "CO"
    CT = "CT"
    DE = "DE"
    FL = "FL"
    GA = "GA"
    HI = "HI"
    ID = "ID"
    IL = "IL"
    IN = "IN"
    IA = "IA"
    KS = "KS"
    KY = "KY"
    LA = "LA"
    ME = "ME"
    MD = "MD"
    MA = "MA"
    MI = "MI"
    MN = "MN"
    MS = "MS"
    MO = "MO"
    MT = "MT"
    NE = "NE"
    NV = "NV"
    NH = "NH"
    NJ = "NJ"
    NM = "NM"
    NY = "NY"
    NC = "NC"
    ND = "ND"
    OH = "OH"
    OK = "OK"
    OR = "OR"
    PA = "PA"
    RI = "RI"
    SC = "SC"
    SD = "SD"
    TN = "TN"
    TX = "TX"
    UT = "UT"
    VT = "VT"
    VA = "VA"
    WA = "WA"
    WV = "WV"
    WI = "WI"
    WY = "WY"
    DC = "DC"